# Generated by Django 3.1.1 on 2020-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('local_copy', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('images', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
