# Generated by Django 3.1.1 on 2020-10-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201005_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='local_copy',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='sku',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ManyToManyField(related_name='images', to='product.Product'),
        ),
    ]
