# Generated by Django 3.1.1 on 2020-10-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201005_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='sku',
            new_name='shop',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='99.99', max_digits=8),
        ),
    ]
